site_name: Cardano S/L
theme: readthedocs
pages:
    - Home: index.md
    - Installation: installation.md
    - Getting Started: getting_started.md
markdown_extensions:
    - toc:
        permalink: True
